/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TodayRouteImport } from './routes/today'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as AssessmentAssessmentIdRouteImport } from './routes/assessment.$assessmentId'
import { Route as FocusIndexRouteImport } from './routes/focus.index'
import { Route as FocusResetRouteImport } from './routes/focus.reset'
import { Route as FocusSessionRouteImport } from './routes/focus.session'
import { Route as HealthIndexRouteImport } from './routes/health.index'
import { Route as HealthVitalsRouteImport } from './routes/health.vitals'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentAssessmentIdRoute = AssessmentAssessmentIdRouteImport.update({
  id: '/assessment/$assessmentId',
  path: '/assessment/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusIndexRoute = FocusIndexRouteImport.update({
  id: '/focus/',
  path: '/focus/',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusResetRoute = FocusResetRouteImport.update({
  id: '/focus/reset',
  path: '/focus/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusSessionRoute = FocusSessionRouteImport.update({
  id: '/focus/session',
  path: '/focus/session',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthVitalsRoute = HealthVitalsRouteImport.update({
  id: '/health/vitals',
  path: '/health/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/today': typeof TodayRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/focus/reset': typeof FocusResetRoute
  '/focus/session': typeof FocusSessionRoute
  '/health/vitals': typeof HealthVitalsRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/focus/': typeof FocusIndexRoute
  '/health/': typeof HealthIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/today': typeof TodayRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/focus/reset': typeof FocusResetRoute
  '/focus/session': typeof FocusSessionRoute
  '/health/vitals': typeof HealthVitalsRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/assessment': typeof AssessmentIndexRoute
  '/focus': typeof FocusIndexRoute
  '/health': typeof HealthIndexRoute
  '/learn': typeof LearnIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/today': typeof TodayRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/focus/reset': typeof FocusResetRoute
  '/focus/session': typeof FocusSessionRoute
  '/health/vitals': typeof HealthVitalsRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/focus/': typeof FocusIndexRoute
  '/health/': typeof HealthIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/onboarding'
    | '/today'
    | '/assessment/$assessmentId'
    | '/focus/reset'
    | '/focus/session'
    | '/health/vitals'
    | '/learn/$lessonId'
    | '/tasks/$taskId'
    | '/assessment/'
    | '/focus/'
    | '/health/'
    | '/learn/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/onboarding'
    | '/today'
    | '/assessment/$assessmentId'
    | '/focus/reset'
    | '/focus/session'
    | '/health/vitals'
    | '/learn/$lessonId'
    | '/tasks/$taskId'
    | '/assessment'
    | '/focus'
    | '/health'
    | '/learn'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/onboarding'
    | '/today'
    | '/assessment/$assessmentId'
    | '/focus/reset'
    | '/focus/session'
    | '/health/vitals'
    | '/learn/$lessonId'
    | '/tasks/$taskId'
    | '/assessment/'
    | '/focus/'
    | '/health/'
    | '/learn/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  TodayRoute: typeof TodayRoute
  AssessmentAssessmentIdRoute: typeof AssessmentAssessmentIdRoute
  FocusResetRoute: typeof FocusResetRoute
  FocusSessionRoute: typeof FocusSessionRoute
  HealthVitalsRoute: typeof HealthVitalsRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  FocusIndexRoute: typeof FocusIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$assessmentId': {
      id: '/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/assessment/$assessmentId'
      preLoaderRoute: typeof AssessmentAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/': {
      id: '/focus/'
      path: '/focus'
      fullPath: '/focus/'
      preLoaderRoute: typeof FocusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/reset': {
      id: '/focus/reset'
      path: '/focus/reset'
      fullPath: '/focus/reset'
      preLoaderRoute: typeof FocusResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/session': {
      id: '/focus/session'
      path: '/focus/session'
      fullPath: '/focus/session'
      preLoaderRoute: typeof FocusSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/vitals': {
      id: '/health/vitals'
      path: '/health/vitals'
      fullPath: '/health/vitals'
      preLoaderRoute: typeof HealthVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  TodayRoute: TodayRoute,
  AssessmentAssessmentIdRoute: AssessmentAssessmentIdRoute,
  FocusResetRoute: FocusResetRoute,
  FocusSessionRoute: FocusSessionRoute,
  HealthVitalsRoute: HealthVitalsRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
  FocusIndexRoute: FocusIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
